### ISSUE TITLE
Asymmetry in the shield attachment points

### ISSUE THREAD

**Issue by Pyro-Fox** [mrjonny2/PNWS#1]
While attempting to slice this design for my printer, I noticed an inconsistency in the attachment points. Is this asymmetry intentional?

**It's very noticeable on the first layer as you can see here:** 
![image](https://user-images.githubusercontent.com/36782094/79514513-2e634d00-7ffb-11ea-9087-4a53062cdb6a.png)

Upon further inspection I can see why. The 2 attachment points at the back of the headband doesn't match the other 4 at the front.

**Here's the symmetrical cross-section:**
![image](https://user-images.githubusercontent.com/36782094/79514721-b5182a00-7ffb-11ea-98ab-eda250b1520c.png)

**And here's what the back ones look like:**
![image](https://user-images.githubusercontent.com/36782094/79514741-c06b5580-7ffb-11ea-80b6-8dfad502e2de.png)

**Comment by mrjonny2** [comment]
You would be correct, that little asymmetry helps give a slightly better hold on the outer parts of the shield
