### ISSUE TITLE
Intersecting faces on solids and missing fillets

### ISSUE THREAD

**Issue by Pyro-Fox** [mrjonny2/PNWS#2]
I promise this is the only other issue I've found. I know that almost every 3D slicer can handle these kind of issues, but I just wanted to document it.

**On the left side of the headband (the side without the R2), there are intersecting faces on both he full and short frames:**
![image](https://user-images.githubusercontent.com/36782094/79542263-28dc2600-8040-11ea-9457-8dde74034810.png)

**This is how it shows up on the released STL:**
![image](https://user-images.githubusercontent.com/36782094/79542612-cfc0c200-8040-11ea-8792-f0170998e549.png)

**And when you take a cross section you can see the intersecting faces:**
![image](https://user-images.githubusercontent.com/36782094/79542873-4067de80-8041-11ea-9d99-4104a87083e8.png)

**Comment by mrjonny2** [comment]
Hi,
Thanks, unfortunately it was a missed radius on the 3D printed part, but shouldn't affect print quality and due to NIH approval we were unable to make that tweak
